### ISSUE TITLE
I got into trouble using this lib in android.

### ISSUE THREAD

**Issue by SSShooter** [januslo/react-native-local-barcode-recognizer#1]
![image](https://user-images.githubusercontent.com/13051472/49359772-15ae0c00-f712-11e8-9bde-0a3ad0eda141.png)

My code is same as the demo code, and iOS is running alright.

**Comment by SSShooter** [comment]
I am sorry, this is a problem of RN.
https://github.com/facebook/react-native/issues/21754

**Comment by januslo** [comment]
Cool man.


发自我的 iPhone
