### ISSUE TITLE
ERROR | attributes: Missing required attribute `homepage`

### ISSUE THREAD

**Issue by HeyShinner** [januslo/react-native-local-barcode-recognizer#7]
"react-native": "0.63.2",
"react-native-local-barcode-recognizer": "0.0.2",

![image](https://user-images.githubusercontent.com/16172530/98059854-13ff9c80-1e83-11eb-8e88-a97d4851cc19.png)

此文件未填写`homepage`导致`pod install` 失败

![image](https://user-images.githubusercontent.com/16172530/98059931-545f1a80-1e83-11eb-9ec1-400f43ccdcd0.png)

**Comment by 0x01001** [comment]
same issue, any solution?

**Comment by QMY-ZQ** [comment]
[点击查看修复步骤](https://github.com/KirillPopovsky/react-native-local-barcode-recognizer/commit/47cca87c16549213c29f549fa986ed687f451981)

**Comment by HeyShinner** [comment]
done
